# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _BASE_NS_/udo-baseos:_BASE_TAG_
ENV UDO_CFG_PATH /etc/hyperledger/udo
RUN mkdir -p /var/hyperledger/production $UDO_CFG_PATH
COPY payload/peer /usr/local/bin
ADD  payload/sampleconfig.tar.bz2 $UDO_CFG_PATH
CMD ["peer","node","start"]
